### ISSUE TITLE
TTS does not switch to Czech when translation direction is switched to uk->cs

### ISSUE THREAD

**Issue by hajic** [ufal/charles-translator-android#1]
Version 0.9.4, when the speaker button is pressed in the uk->cs direction, it still uses the uk synthesis.

**Comment by krabatom** [comment]
I can´t reproduce this issue. Could you provide exact steps and text? Maybe your TTS does not support uk. Can you try https://play.google.com/store/apps/details?id=com.google.android.tts&hl=cs&gl=US ?

**Comment by krabatom** [comment]
fixed in version 0.9.5
