### ISSUE TITLE
Strange history item click event action

### ISSUE THREAD

**Issue by matyaskopp** [ufal/charles-translator-android#12]
I translated the word "Ahoj":

![Screenshot_20220421-211356](https://user-images.githubusercontent.com/5867995/164538635-18218790-fd8a-4974-8734-f499971d76bd.png)

Then I pressed history icon:

![Screenshot_20220421-212025](https://user-images.githubusercontent.com/5867995/164538737-4abd9f0c-4b00-46d0-bcf5-448ee2613f28.png)

and then a card with the history item containing the translation of "Ahoj":

![Screenshot_20220421-212043](https://user-images.githubusercontent.com/5867995/164538874-2c0ae43d-b915-4807-bd21-e4d982526bf1.png)

**I expected that the first screenshot would appear.**

**Comment by krabatom** [comment]
It is bug. I will fix it. Thank you for report.

**Comment by krabatom** [comment]
It should be fixed in version 0.9.14
