### ISSUE TITLE
History back arrow doesn't return to previous state

### ISSUE THREAD

**Issue by matyaskopp** [ufal/charles-translator-android#13]
Starting with an empty text field:
![Screenshot_20220421-215511](https://user-images.githubusercontent.com/5867995/164542635-f3eeb891-f584-4d94-a79a-ce77e6f6ed41.png)

pressing history icon:
![Screenshot_20220421-215534](https://user-images.githubusercontent.com/5867995/164542697-c91b5b41-f394-4345-98c5-faf9b69f90e7.png)

pressing back arrow:
![Screenshot_20220421-215619](https://user-images.githubusercontent.com/5867995/164542761-82df7f4a-732c-4267-acd0-2b0daf72075a.png)

**I have expected an empty text field**

**Comment by krabatom** [comment]
It is bug. I will fix it. Thank you for report.

**Comment by krabatom** [comment]
It should be fixed in version 0.9.14
