### ISSUE TITLE
Crashes on Chromebook

### ISSUE THREAD

**Issue by martinpopel** [ufal/charles-translator-android#14]
The app crashes when clicking on some history items. Other items work OK, but I could not find any rule which items cause the crashes and which not.
I have Chrome OS 100.0.4896.82, Acer N15Q8. I have tried just a few Android apps and all worked correctly, but I admit that using an old chromebook is an edge case. So maybe we can close this issue as "wont fix" (and similarly #11) if no one else encounters the same bug.

**Comment by krabatom** [comment]
It is bug. I will fix it. Thank you for report.

**Comment by krabatom** [comment]
It should be fixed in version 0.9.14

**Comment by martinpopel** [comment]
Yes. This is fixed. Thanks.
