### ISSUE TITLE
Use anonymous identifier instead of IP address for logging

### ISSUE THREAD

**Issue by stranak** [ufal/charles-translator-android#17]
If the user says OK to giving us their data, generate and use an anonymous identifier unigue per device instead of IP address.

- better privacy 
- better logging, beucase we get all the data grouped by that one user, not their various IP addresses as the phone moves around.

**Comment by martinpopel** [comment]
I agree this is a good idea. @kosarko should introduce a new parameter (or header?) in the API for this unique id (and then use it instead of the IP address). We cannot reuse the `author` parameter because several persons (on several devices) from the same (humanitarian or other) organization may want to use the same `author` (also, `author` is filled in by the user).

**Comment by stranak** [comment]
Could we reuse the author anyway, and concatenate it, if a user-generated string is filled-in?

normal user who agrees to data collection: `893e9eaa99d518bf4f97b557a224af5a0abc046d`
user from a humanitarian organisation: `893e9eaa99d518bf4f97b557a224af5a0abc046d_ADRA`

This would still give us the user-filled names easily, and also give us devices per organisation, all without changes to API and with improved privacy (once we delete the IP addresses from collected data)

**Comment by martinpopel** [comment]
I think device ID (discussed in this issue) should be kept separate from the `author` parameter, which is actually "organization name" (used by possibly many people on many devices, as I wrote above). I don't see any advantage in merging these two parameters into one (even if anyone can still split on underscore, but that would mean adding `join` and `split` everywhere in the code).

**Comment by stranak** [comment]
after further thought, do we need this at all? I thought it would simplify things, but it rather looks like an unnecessary complication that doesn't really improve anything important.

So, close as `wontfix`?

**Comment by martinpopel** [comment]
Yes, in the end I vote for close this as `wontfix`.
It could be useful, but we don't necessarily need it and adding the extra parameter in API would be an extra work.

**Comment by krabatom** [comment]
Ok, I am closing this issue
