### ISSUE TITLE
The content of input field when microphone is activated

### ISSUE THREAD

**Issue by matyaskopp** [ufal/charles-translator-android#20]
When the microphone icon is pressed, the input field should be erased. 

The input field in the second screenshot should be empty:
![image](https://user-images.githubusercontent.com/5867995/165063337-6c868dcf-21f4-4f48-a571-92b697428722.png)
The current situation can be confusing - users can expect that the recorded text is appended (inserted) into the current text in the input field.

**Comment by martinpopel** [comment]
Yes. The feature of appending (or inserting) recorded text to the previous content could be useful in some rare cases, but it would complicate the main use case, where the users expect that the previous content is deleted immediately after using the mic icon.
(If there was a "valuable" text, the users can always find it in the history, so the deleting makes no harm.)

**Comment by matyaskopp** [comment]
I did not want to have an append function. 
I just wanted to make it obvious that the current input field content will be erased. 
Only change the order: firstly remove the text and then record a new one. 

I think it should behave the same way when you use the keyboard - you remove current text and write a new one.

**Comment by martinpopel** [comment]
I agree. We don't want the append function for audio input. This issue is about deleting the previous input text *immediately* after tapping the mic icon.

With the keyboard input the users can decide whether to delete the previous input (e.g. using the delete button) or whether to append/insert the new text - that's OK, of course.

**Comment by matyaskopp** [comment]
> I agree. We don't want the append function for audio input. This issue is about deleting the previous input text immediately after tapping the mic icon

Exactly

**Comment by krabatom** [comment]
changed in version 0.9.15
