### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by stranak** [ufal/charles-translator-android#22]
New icon, "Charles Translator".
- [ ] pick one (Slack)
- [ ] get feedback for that one (Slack)
- [ ] have the author improve it based on the feedback
- [ ] check with the author that the icon conforms to [the guidelines](https://developer.android.com/distribute/google-play/resources/icon-design-specifications)

**Comment by hladkab** [comment]
[charles_translator_02.pdf](https://github.com/ufal/lindat-translation-android/files/8619332/charles_translator_02.pdf)
[charles_translator_01.pdf](https://github.com/ufal/lindat-translation-android/files/8619334/charles_translator_01.pdf)

**Comment by krabatom** [comment]
If you split it as icon.svg and square_background.svg, I can generate via Android Studio more icons.
![image](https://user-images.githubusercontent.com/12136816/166673902-db66fdbc-677c-46c3-b9df-9594b0683ec9.png)

**Comment by martinpopel** [comment]
Meanwhile, we have agreed (I hope definitely) on yet another variant:
[charles_translator_03.pdf](https://github.com/ufal/lindat-translation-android/files/8622139/charles_translator_03.pdf)

**Comment by krabatom** [comment]
new logo is used in version 0.9.17
