### ISSUE TITLE
finalize the About text

### ISSUE THREAD

**Issue by stranak** [ufal/charles-translator-android#23]
What needs to be finalized:
- [ ] remove the web frontend credits
- [ ] add the option to create github issues
- [ ] update localizations

**Comment by krabatom** [comment]
@stranak is this ok for you?
![Screenshot_20220504_173328](https://user-images.githubusercontent.com/12136816/166717310-83f44f59-0cab-4110-ba97-a09f2a14e5cf.png)

**Comment by stranak** [comment]
Fine with me, @hajic ?

**Comment by hladkab** [comment]
- nadpis Charles Translator for Ukraine
- [x] Lindat tým -> LINDAT tým
- [x] Poslední odstavec: Dotazy ohledně toho překladače posílejte prosím na adresu u4u@ufal.mff.cuni. Chyby můžete hlásit i na Githubu.

**Comment by krabatom** [comment]
![Screenshot_20220505_182438](https://user-images.githubusercontent.com/12136816/166968760-48546a28-b415-43d7-a42c-0a83e7c47e07.png)

Opraveno podle posledních připomínek

**Comment by krabatom** [comment]
changed in version 0.9.17

**Comment by hajic** [comment]
For me, too. 

Will you please check the localizations (en, uk, sk) if the structure corresponds to this? 

JH

**Comment by krabatom** [comment]
@hajic actual screenshots:
![Screenshot_20221011_172218](https://user-images.githubusercontent.com/12136816/195133423-5537abf5-fe3e-43ec-9c56-c6d5bbda4b54.png)
![Screenshot_20221011_172243](https://user-images.githubusercontent.com/12136816/195133431-80a379f4-979e-4713-86e7-42ec6032dbdf.png)
![Screenshot_20221011_172336](https://user-images.githubusercontent.com/12136816/195133442-1cc35e6c-48e2-413e-acd3-ab1495cc8f88.png)
![Screenshot_20221011_172354](https://user-images.githubusercontent.com/12136816/195133454-5904a3a6-a619-4bfb-b611-e55d4b39e442.png)
