### ISSUE TITLE
review Ukrainian localisation

### ISSUE THREAD

**Issue by stranak** [ufal/charles-translator-android#26]
https://github.com/ufal/lindat-translation-android/blob/master/app/src/main/res/values-uk/strings.xml

**Comment by krabatom** [comment]
source texts https://github.com/ufal/lindat-translation-android/blob/master/app/src/main/res/values-cs/strings.xml

**Comment by hladkab** [comment]
@krabatom Mariia Anisimova promised to review the UA version. Tomáš, please, can you access the text so she can edit it on-line in a web browser?

**Comment by krabatom** [comment]
Mariia finished localisation, so I am closing this issue
