### ISSUE TITLE
review English localisation

### ISSUE THREAD

**Issue by stranak** [ufal/charles-translator-android#27]
https://github.com/ufal/lindat-translation-android/blob/master/app/src/main/res/values/strings.xml

**Comment by krabatom** [comment]
source texts https://github.com/ufal/lindat-translation-android/blob/master/app/src/main/res/values-cs/strings.xml

**Comment by hladkab** [comment]
@stranak @hajic po konzultaci s @krabatom jsem editovala českou a anglickou verzi. Ukrajinskou verzi projde Marija (pošlu ji i anglickou verzi, aby rozuměla správně)

**Comment by krabatom** [comment]
So, I am closing this issue :-)
