### ISSUE TITLE
Text remains in input window when direction is swapped

### ISSUE THREAD

**Issue by hajic** [ufal/charles-translator-android#3]
version 0.9..4: When the translation direction is reversed, the text in the input window stay (e.g. the Czech text stays in the upper window which is now Ukrainian), and it is translated to cs (usually remains the same, but it is confusing). Suggestion: move the translated text from the output window to the input window at each reversal.

**Comment by krabatom** [comment]
This behaviour was inspired by web version https://lindat.cz/translation, but true is, that other translation apps behave like you described. So I will do it same.

**Comment by martinpopel** [comment]
see https://github.com/ufal/uk-cs-translator/issues/15#issuecomment-1078950859

**Comment by krabatom** [comment]
That's interesting. I tried DeepL, Microsoft Translator and they swap it. Google Translator doesn't swap it, but it shows some hint. So maybe both approaches are correct.

**Comment by martinpopel** [comment]
My personal preference would be to switch the texts when clicking the "switch language" button. Google Translate (at least the web version) does it as well.
In addition, we should allow to choose the language direction by clicking on the source/target language name. While supporting only Czech and Ukrainian it is not necessary, but we will need in future, when adding more languages, anyway. When changing the source language this way, the source text should stay.

**Comment by hajic** [comment]
I agree with Martin, very much so.JH
-------- Original message --------From: Martin Popel ***@***.***> Date: 4/10/22  12:51  (GMT+01:00) To: ufal/lindat-translation-android ***@***.***> Cc: Jan Hajic ***@***.***>, Author ***@***.***> Subject: Re: [ufal/lindat-translation-android] Text remains in input window when direction is swapped (Issue #3) 
My personal preference would be to switch the texts when clicking the "switch language" button. Google Translate (at least the web version) does it as well.
In addition, we should allow to choose the language direction by clicking on the source/target language name. While supporting only Czech and Ukrainian it is not necessary, but we will need in future, when adding more languages, anyway. When changing the source language this way, the source text should stay.

**Comment by krabatom** [comment]
Ok, so if I understand it correctly, for now in app switch button will switch the texts and later we will add popup menu with languages selection.

**Comment by krabatom** [comment]
fixed in version 0.9.5
