### ISSUE TITLE
Back button needs to be pressed multiple times

### ISSUE THREAD

**Issue by kasnerz** [ufal/charles-translator-android#30]
The system back button on the bottom bar needs to be pressed multiple times:
- 2x in order to return from the list of previous translations to the main screen.
- 3x in order to return from the list of favourite translations to the main screen.

The intermediate button clicks do nothing (only make the title bar slightly brighter). 

(The in-app return button in the top left corner works without any issues, this is just about the system back button which some newer Android versions may not even have.)

**Technical details:** Xperia XZ1 Compact, Android 9, app version 0.9.16

**Comment by krabatom** [comment]
should be fixed in version 0.9.17
