### ISSUE TITLE
Googleboard voice input gets cut off early

### ISSUE THREAD

**Issue by hajic** [ufal/charles-translator-android#4]
version 0.9.4: when using the ASR called from the Google keyboard, it often gets truncated (sometimes even after the first word). This does not happen when speaking through the Gogole keyboard to the web version of the translation. So it must be some sync issue within the app.

**Comment by krabatom** [comment]
You are right. I will try to fix it.

**Comment by krabatom** [comment]
fixed in version 0.9.10
