### ISSUE TITLE
ASR input: previous text content appeares when removed current translation and asr mode still activated

### ISSUE THREAD

**Issue by matyaskopp** [ufal/charles-translator-android#51]
1. press the mic button
2. say a word: "jedna"
3. then press cross to remove word "1" (now the input area is empty)
4. then say another word: "dva"
5. finally, "1 2" appear in the input area

**Comment by martinpopel** [comment]
I confirm this bug (only in the newest Beta 1.0.3, not in the official stable version). A simple solution may be: stop recording when the user deletes the input (that's what other similar apps do, if they show the "X" delete button at all).

Another unexpected behavior: when moving the cursor in the middle of the text while recording, the new words are still added at the end. A simple solution: stop recording when the users taps the input box (Google style) OR don't allow moving the cursor in the input box when recording (Microsoft style).

**Comment by krabatom** [comment]
Yes, after some user interaction (click on cross, start type etc.) should ASR stop listening. I will fix it. Thank you

**Comment by krabatom** [comment]
should be fixed in version 1.0.4
