### ISSUE TITLE
Text input does weird stuff with MessagEase keyboard

### ISSUE THREAD

**Issue by jlibovicky** [ufal/charles-translator-android#7]
I am using a rather unusual keyboard called [MessagEase](https://play.google.com/store/apps/details?id=com.exideas.mekb&hl=cs&gl=US). With this keyboard, diacritics are added to already written characters, i.e. I write "s", then do "add háček" and the result is "š". This does not work here, it writes a standalone "ˇ" character. Often, the following character also got malformed. I use the keyboard for several years and I have never encountered an issue like this.

version 0.9.7, Samsung M22, Android 11, Kernel 4.14.186-22735277

**Comment by krabatom** [comment]
I will need more info how reproduce this bug. I downloaded MessagEase, but I don't now, how to "add háček".

**Comment by tuetschek** [comment]
@krabatom to "add háček", you put your finger on the "N" key and then quickly drag a little to the top (in the direction of the "^" mark) & back to bottom.

**Comment by krabatom** [comment]
@tuetschek thank you. It does not work for me, but @jlibovicky showed me, ho to do á and it should be fixed in version 0.9.13
