### ISSUE TITLE
Joining sentences in output window omits space.

### ISSUE THREAD

**Issue by hajic** [ufal/charles-translator-android#9]
When the input text consists of several sentences (tested with idnes text with fullstops at the end of sentences), they end up joined without space after the fullstop in the output window. The browser UI does not do it, so it has to do something with the app.

**Comment by krabatom** [comment]
I can't reproduce this issue. Can you provide exact text?

**Comment by hajic** [comment]
Již před vznikem Československa měli Češi hojné kontakty s ruskou intelektuální elitou. V tomhle ohledu určitě vyčnívá Karel Kramář, první československý premiér a díky své manželce i romantický rusofil. K Rusku Kramář obdivně vzhlížel a po vypuknutí první světové války snil, že nás ruská vojska osvobodí z područí jha habsburského a kůň ruského kozáka se napije z Vltavy.

**Comment by hajic** [comment]
Oitput: Ще до створення Чехословаччини чехи мали тісні контакти з російською інтелектуальною елітою.У цьому плані обов'язково виділяється Карел Крамар, перший прем'єр-міністр Чехословаччини і, завдяки дружині, романтичний русофіл.До Росії Крамар захоплено дивився, і з початком Першої світової війни мріяв, що російські війська звільнять нас з-під ярма габсбурзького, а кінь російського козака вип'є з Влтави.

**Comment by krabatom** [comment]
Thank you, I can reproduce it. I will try to fix it.

**Comment by krabatom** [comment]
it should be fixed in version 0.9.13
